import {
  ClassicEditor as ClassicEditorBase,
  Alignment,
  Autoformat,
  AutoImage,
  BalloonToolbar,
  BlockQuote,
  Bold,
  Code,
  CodeBlock,
  Essentials,
  FileRepository,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  Highlight,
  ImageBlock,
  ImageInline,
  ImageInsertViaUrl,
  ImageResize,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  List,
  ListProperties,
  MediaEmbed,
  Paragraph,
  RemoveFormat,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCellProperties,
  TableColumnResize,
  TableToolbar,
  Underline,
  PluginConstructor,
  LinkDecoratorDefinition,
} from 'ckeditor5';
import LinkFormExtension from './plugins/LinkFormExtension';

import 'ckeditor5/ckeditor5.css';

export default class ClassicEditor extends ClassicEditorBase {
  static defaultConfig = {
    toolbar: {
      items: [
        "heading",
        "fontSize",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "code",
        "codeBlock",
        "blockQuote",
        "removeFormat",
        "|",
        "subscript",
        "superscript",
        "|",
        "fontFamily",
        "fontColor",
        "highlight",
        "|",
        "indent",
        "outdent",
        "bulletedList",
        "numberedList",
        "alignment",
        "|",
        "insertTable",
        "imageUpload",
        "link",
        "mediaEmbed",
      ],
      shouldNotGroupWhenFull: false,
    },
    plugins: [
      LinkFormExtension,
      Alignment,
      Autoformat,
      AutoImage,
      BalloonToolbar,
      BlockQuote,
      Bold,
      Code,
      CodeBlock,
      Essentials,
      FileRepository,
      FontColor,
      FontFamily,
      FontSize,
      Heading,
      Highlight,
      ImageBlock,
      ImageInline,
      ImageInsertViaUrl,
      ImageResize,
      ImageUpload,
      Indent,
      IndentBlock,
      Italic,
      Link,
      List,
      ListProperties,
      MediaEmbed,
      Paragraph,
      RemoveFormat,
      Strikethrough,
      Subscript,
      Superscript,
      Table,
      TableCellProperties,
      TableColumnResize,
      TableToolbar,
      Underline,
    ],
    balloonToolbar: [
      "bold",
      "italic",
      "|",
      "link",
      "|",
      "bulletedList",
      "numberedList",
    ],
    licenseKey: "GPL",
    language: "en",
    fontFamily: {
      supportAllValues: true,
    },
    table: {
      contentToolbar: [
        "tableColumn",
        "tableRow",
        "mergeTableCells",
        "tableCellProperties",
      ],
    },
    link: {
      defaultProtocol: "https://",
      decorators: {
        openInNewTab: {
          mode: "manual",
          label: "Open in a new tab",
          attributes: {
            target: "_blank",
            rel: "noopener noreferrer",
          },
        },
      },
      toolbar: [ 'linkPreview',
    '|',
    'editLink',
    'unlink' ],
    },
    mediaEmbed: {
      removeProviders: [
        "spotify",
        "instagram",
        "twitter",
        "googleMaps",
        "flickr",
        "facebook",
      ],
    },
    heading: {
      options: [
        {
          model: "paragraph",
          title: "Paragraph",
          class: "ck-heading_paragraph",
        },
        {
          model: "heading1",
          view: "h1",
          title: "Heading 1",
          class: "ck-heading_heading1",
        },
        {
          model: "heading2",
          view: "h2",
          title: "Heading 2",
          class: "ck-heading_heading2",
        },
        {
          model: "heading3",
          view: "h3",
          title: "Heading 3",
          class: "ck-heading_heading3",
        },
        {
          model: "heading4",
          view: "h4",
          title: "Heading 4",
          class: "ck-heading_heading4",
        },
        {
          model: "heading5",
          view: "h5",
          title: "Heading 5",
          class: "ck-heading_heading5",
        },
        {
          model: "heading6",
          view: "h6",
          title: "Heading 6",
          class: "ck-heading_heading6",
        },
        // To format <pre> properly (summernote compatability).
        // CKEditor will change it to <pre><code> but on edit it will render properly
        {
          // @ts-ignore
          model: "formatted",
          view: "pre",
          title: "Formatted",
        },
      ],
    },
  };
}
